# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build for Testing"
  lane :build_for_testing do
    scan(
      clean: true,
      build_for_testing: true
    )
  end

  desc "Test without Building"
  lane :test_without_building do
    scan(
      test_without_building: true
    )
  end

  desc "Build for UI Testing"
  lane :build_for_ui_testing do
    scan(
      clean: true,
      build_for_testing: true,
      testplan: "PingUI"
    )
  end

  desc "Test without Building"
  lane :ui_test_without_building do
    scan(
      test_without_building: true,
      testplan: "PingUI"
    )
  end
end

platform :mac do
  desc "Build for Testing"
  lane :build_for_testing do
    scan(
      clean: true,
      build_for_testing: true,
      destination: "platform=macOS"
    )
  end

  desc "Test without Building"
  lane :test_without_building do
    scan(
      test_without_building: true,
      destination: "platform=macOS"
    )
  end

  desc "Build for UI Testing"
  lane :build_for_ui_testing do
    scan(
      clean: true,
      build_for_testing: true,
      testplan: "PingUI",
      destination: "platform=macOS"
    )
  end

  desc "Test without Building"
  lane :ui_test_without_building do
    scan(
      testplan: "PingUI",
      test_without_building: true,
      destination: "platform=macOS"
    )
  end
end
