name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "ci-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.1.app

jobs:
  build-and-test:
    name: Build and Test (${{ matrix.name }})
    runs-on: macos-13
    strategy:
      matrix:
        include:
          - name: iPhone
            destination: platform=iOS Simulator,name=iPhone 15,OS=17.0.1
            sdk: iphonesimulator17.0
          - name: macOS
            destination: platform=macOS
            sdk: macosx14.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          set -o pipefail && env NSUnbufferedIO=YES && xcodebuild build-for-testing -scheme Ping -sdk macosx14.0 -testPlan Ping -destination '${{ matrix.destination }}' | xcpretty
      
      - name: Test
        run: |
          set -o pipefail && env NSUnbufferedIO=YES && xcodebuild test-without-building -scheme Ping -testPlan Ping -destination '${{ matrix.destination }}' | xcpretty
