name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "ci-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.0.app/Contents/Developer

jobs:
  build-and-test-ios:
    name: Build and Test (iOS)
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build
        run: bundle exec fastlane ios build_for_testing
      
      - name: Test
        run: bundle exec fastlane ios test_without_building

  build-and-test-macos:
    name: Build and Test (macOS)
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build
        run: bundle exec fastlane mac build_for_testing
      
      - name: Test
        run: bundle exec fastlane mac test_without_building
        